# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generator/generator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'generator/generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19generator/generator.proto\x12\tgenerator\"\"\n\x0fGenerateRequest\x12\x0f\n\x07\x61rchive\x18\x01 \x01(\x0c\"g\n\x10GenerateResponse\x12\x13\n\x0bzip_archive\x18\x01 \x01(\x0c\x12%\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x15.generator.FileErrors\x12\x17\n\x0fgenerated_count\x18\x03 \x01(\x05\"E\n\nFileErrors\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12$\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x14.generator.FileError\"*\n\tFileError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\tGenerator\x12\x43\n\x08Generate\x12\x1a.generator.GenerateRequest\x1a\x1b.generator.GenerateResponseB0Z.agreements-generator/proto/generator;generatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator.generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.agreements-generator/proto/generator;generator'
  _globals['_GENERATEREQUEST']._serialized_start=40
  _globals['_GENERATEREQUEST']._serialized_end=74
  _globals['_GENERATERESPONSE']._serialized_start=76
  _globals['_GENERATERESPONSE']._serialized_end=179
  _globals['_FILEERRORS']._serialized_start=181
  _globals['_FILEERRORS']._serialized_end=250
  _globals['_FILEERROR']._serialized_start=252
  _globals['_FILEERROR']._serialized_end=294
  _globals['_GENERATOR']._serialized_start=296
  _globals['_GENERATOR']._serialized_end=376
# @@protoc_insertion_point(module_scope)
